export enum TechnologyName {
  REACTJS = 'React.js', // Core library for building the app
  CSS = 'CSS',
  HTML = 'HTML',
  JAVASCRIPT = 'JavaScript',
  POSTGRESQL = 'PostgreSQL',
  NESTJS = 'NestJS', // Backend framework
  YARN_BERRY = 'Yarn\u00A0Berry', // Package manager
  NPM = 'npm', // Package manager
  TYPESCRIPT = 'TypeScript', // Strongly typed JavaScript
  JAVASCRIPT_ES6_PLUS = 'JavaScript\u00A0(ES6+)', // Modern JS content with non-breaking space
  CREATE_REACT_APP = 'Create\u00A0React\u00A0App', // React setup tool
  VITE = 'Vite', // Modern build tool
  REACT_ROUTER = 'React\u00A0Router', // SPA navigation and routing
  AXIOS = 'Axios', // API request library
  FETCH = 'Fetch', // API request method
  REACT_QUERY = 'React\u00A0Query', // Data fetching and caching
  REDUX = 'Redux', // State management library
  ZUSTAND = 'Zustand', // State management library
  RECOIL = 'Recoil', // State management library
  STYLED_COMPONENTS = 'Styled\u00A0Components', // CSS-in-JS styling tool
  CSS_MODULES = 'CSS\u00A0Modules', // Modular CSS
  TAILWIND_CSS = 'Tailwind\u00A0CSS', // Utility-first CSS framework
  WEBPACK = 'Webpack', // Module bundler
  REACT_TESTING_LIBRARY = 'React\u00A0Testing\u00A0Library', // React testing tool
  JEST = 'Jest', // Testing framework Jest
  ESLINT = 'ESLint', // Code linting tool
  PRETTIER = 'Prettier', // Code formatting tool
  STORYBOOK = 'Storybook', // UI component tool
  NODEJS = 'Node.js', // Backend runtime environment
  EXPRESS = 'Express', // Web framework for Node.js
  MICROSERVICES = 'Microservices', // Architectural pattern
  RABBITMQ = 'RabbitMQ', // Message broker
  WEBSOCKET = 'WebSocket', // Communication protocol
  DOCKER = 'Docker', // Containerization tool
  KUBERNETES = 'Kubernetes', // Container orchestration
  JENKINS = 'Jenkins', // Continuous integration tool
  SOLID = 'SOLID', // Design principles
  HEXAGONAL_ARCHITECTURE = 'Hexagonal\u00A0Architecture', // Software design pattern
  SAGA = 'SAGA', // Distributed transaction pattern
}
